const ROOT_ACTIONS_SOME_THING = 'ROOT_ACTIONS_SOME_THING'
const ROOT_MUTATION_SOME_THING = 'ROOT_MUTATION_SOME_THING'
const ROOT_GETTERS_SOME_THING = 'ROOT_GETTERS_SOME_THING'

export {
  ROOT_ACTIONS_SOME_THING,
  ROOT_MUTATION_SOME_THING,
  ROOT_GETTERS_SOME_THING
}
