const MODULES_A_CHILD_ONE_ACTION = 'MODULES_A_CHILD_ONE_ACTION'
const MODULES_A_CHILD_ONE_GETTERS = 'MODULES_A_CHILD_ONE_GETTERS'
const MODULES_A_CHILD_ONE_MUTATIONS = 'MODULES_A_CHILD_ONE_MUTATIONS'

export {
  MODULES_A_CHILD_ONE_ACTION,
  MODULES_A_CHILD_ONE_GETTERS,
  MODULES_A_CHILD_ONE_MUTATIONS
}
